name: update third party license information

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Install gocomply
        run: go install tawesoft.co.uk/gopkg/gocomply@v0.7.1
      - name: Execute gocomply
        run: gocomply > cmd/licenses/3rd-party-licenses.txt
      - name: Commit if changes are present
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add cmd/licenses/3rd-party-licenses.txt
            git commit -m "Updating license information"
            git push
          else
            echo "no changes"
          fi